# Generated by Django 4.1.4 on 2022-12-15 10:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rating_name', models.IntegerField(choices=[(1, 'Dobry'), (2, 'Umiarkowany'), (3, 'Ryzykowny')])),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('number_NIP', models.BigIntegerField(null=True, unique=True)),
                ('active', models.BooleanField(default=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('deadline', models.DateField(default=datetime.date(2022, 12, 15), null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyapp.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyRatios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_name', models.IntegerField()),
                ('assets_fixed', models.FloatField()),
                ('assets_current', models.FloatField()),
                ('stock', models.FloatField()),
                ('receivables_short_term', models.FloatField()),
                ('receivables_trade', models.FloatField()),
                ('receivables_tax', models.FloatField()),
                ('investments_short_term', models.FloatField()),
                ('assets_cash', models.FloatField()),
                ('assets_total', models.FloatField()),
                ('equity', models.FloatField()),
                ('capital_share', models.FloatField()),
                ('provision_and_accruals', models.FloatField()),
                ('liabilities_long_therm', models.FloatField()),
                ('liabilities_long_therm_financial', models.FloatField()),
                ('liabilities_short_therm', models.FloatField()),
                ('liabilities_short_therm_financial', models.FloatField()),
                ('liabilities_short_therm_trade', models.FloatField()),
                ('liabilities_and_equity', models.FloatField()),
                ('revenue', models.FloatField()),
                ('profit_operating', models.FloatField()),
                ('depreciation', models.FloatField()),
                ('profit_gross', models.FloatField()),
                ('tax_income', models.FloatField()),
                ('profit_net', models.FloatField()),
                ('capitalization', models.FloatField()),
                ('current_ratio', models.FloatField()),
                ('debt_ratio', models.FloatField()),
                ('debt_to_equity_ratio', models.FloatField()),
                ('receivables_turnover_ratio', models.FloatField()),
                ('liabilities_turnover_ratio', models.FloatField()),
                ('profit_operating_margin', models.FloatField()),
                ('profit_net_margin', models.FloatField()),
                ('debt_financial_net', models.FloatField()),
                ('ebitda', models.FloatField()),
                ('debt_financial_net_to_ebitda', models.FloatField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyapp.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyapp.company')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='category_ratios',
            field=models.ManyToManyField(through='companyapp.CompanyRatios', to='companyapp.category'),
        ),
        migrations.AddField(
            model_name='company',
            name='trade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='companyapp.trade'),
        ),
    ]
