# Generated by Django 4.1.4 on 2022-12-16 07:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyratios',
            old_name='liabilities_short_therm_trade',
            new_name='liabilities_trade',
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(default=datetime.date(2022, 12, 16), null=True),
        ),
    ]
